name: newApp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0" 

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.9.7+2
  image: ^2.0.7
  animator: 0.1.4
  image_picker: 
  google_sign_in: ^4.0.1+1
  timeago: 2.0.17
  cached_network_image:
  firebase_auth: ^0.8.3
  multi_image_picker: ^4.7.14
  shared_preferences: ^0.5.12+4
  font_awesome_flutter: ^8.11.0
  geolocator: ^5.0.5
  uuid: ^2.0.0
  fluttertoast: ^7.1.6
  flutter_signin_button: ^1.1.0
  cupertino_icons: ^0.1.2
  path_provider: ^0.5.0+1
  firebase_messaging: ^4.0.0+1
  firebase_storage: ^2.1.0+1
  flutter_svg:
  flutter_staggered_grid_view: ^0.3.2
  smooth_star_rating:
  webview_flutter:
  url_launcher:
  stop_watch_timer: ^0.6.0+1
  http:
  
  provider: ^4.0.1
  transparent_image: ^0.1.0
  flutter_spinkit: ^4.1.2
  flutter_typeahead: ^1.8.1
  
  stripe_payment: ^1.0.7
  carousel_pro: ^1.0.0
  carousel_slider:
  
  flutter_rating_bar: ^3.2.0+1
  share: ^0.6.4+3
  flutter_screenutil: ^3.2.0
  logger: ^0.9.4
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/
    - assets/icons/
    
    